language: node_js
node_js:
- 0.1
addons:
  sauce_connect: true
env:
  global:
  - secure: Sxxrf+TxYLWC2WMBFkvCbHHfutcETRCG5HDzyKYlIu0lFm830faloa6QIDcKikIORDqTP5U0HWP82UmOYl2Mq19JiJzoFfWYHFZ1HjXrsnSqc1kvlfiLxfxuhUaSUdfjW3ZKPy+wT3zj4fJkrbMHr07jdQi3gG7qdLEjy/AUpPI=
  - secure: B6Wy1LBFhr/3gEame0op0S29i7t48IQBDMy5kN5RYhUZjvum3ih1OAOPQMecFASOTwKIIm6Z+A/cPWYc5ytMvHd7bVsRHOeYvCoUDpZAGsU9ClwLng1gm63C+6xgpxKMn3dIVNj6hmrM+kStnCE1eJfVeiD/ZmMI91JYocOlrs8=
before_install:
- npm install -g grunt-cli
